let pokedexJson = [
    {id:1, img:'images/003.png', number:'n°003', name:'Venusaur', type:[{type1:'Grass',type2:'Poison'}], weakness:[{weakness1:'Flying', weakness2:'Fire', weakness3:'Ice'}], description:'Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.'},
    {id:2, img:'images/006.png', number:'n°006', name:'Charizard', type:[{type1:'Fire',type2:'Flying'}], weakness:[{weakness1:'Water', weakness2:'Electric', weakness3:'Rock'}], description:'It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.'},
    {id:3, img:'images/009.png', number:'n°009', name:'Blastoise', type:[{type1:'Water',type2:''}], weakness:[{weakness1:'Grass', weakness2:'Electric', weakness3:''}], description:'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.'},
    {id:4, img:'images/011.png', number:'n°011', name:'Metapod', type:[{type1:'Bug',type2:''}], weakness:[{weakness1:'Fire', weakness2:'Flying', weakness3:'Rock'}], description:'It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack.'},
    {id:5, img:'images/018.png', number:'n°018', name:'Pidgeot', type:[{type1:'Normal',type2:'Flying'}], weakness:[{weakness1:'Electric', weakness2:'Ice', weakness3:'Rock'}], description:'This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.'},
    {id:6, img:'images/025.png', number:'n°025', name:'Pikachu', type:[{type1:'Electric',type2:''}], weakness:[{weakness1:'Ground', weakness2:'', weakness3:''}], description:'Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.'},
    {id:7, img:'images/035.png', number:'n°035', name:'Clefairy', type:[{type1:'Fairy',type2:''}], weakness:[{weakness1:'Steel', weakness2:'Poison', weakness3:''}], description:'It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon.'},
    {id:8, img:'images/057.png', number:'n°057', name:'Primeape', type:[{type1:'Fighting',type2:''}], weakness:[{weakness1:'Psychic', weakness2:'Flying', weakness3:'Fairy'}], description:'It stops being angry only when nobody else is around. To view this moment is very difficult.'},
    {id:9, img:'images/094.png', number:'n°094', name:'Gengar', type:[{type1:'Ghost',type2:'Poison'}], weakness:[{weakness1:'Ghost', weakness2:'Dark', weakness3:'Psychic'}], description:'On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.'},
    {id:10, img:'images/105.png', number:'n°105', name:'Maroak', type:[{type1:'Ground',type2:''}], weakness:[{weakness1:'Water', weakness2:'Grass', weakness3:'Ice'}], description:'This Pokémon overcame its sorrow to evolve a sturdy new body. Marowak faces its opponents bravely, using a bone as a weapon.'},
    {id:11, img:'images/149.png', number:'n°149', name:'Dragonite', type:[{type1:'Dragon',type2:'Flying'}], weakness:[{weakness1:'Dragon', weakness2:'Ice', weakness3:'Rock'}], description:'It’s a kindhearted Pokémon. If it spots a drowning person or Pokémon, Dragonite simply must help them.'},
    {id:12, img:'images/208.png', number:'n°208', name:'Steelix', type:[{type1:'Steel',type2:'Ground'}], weakness:[{weakness1:'Fire', weakness2:'Water', weakness3:'Fighting'}], description:'It is said that if an Onix lives for over 100 years, its composition changes to become diamond-like.'}
];